### ISSUE TITLE
Multi Store only shows on Default config

### ISSUE THREAD

**Issue by gabehou** [pmclain/module-stripe#10]
I have a multi store setup with with different domains and it is not displaying for the website scope.

**Comment by pmclain** [comment]
What exactly is missing from the website scope? All the options?

**Comment by gabehou** [comment]
Yes, under Payment methods for the store the option for stripe does not display at all.

**Comment by pmclain** [comment]
I went back and looked at the Magento core payment modules and the scope granularity on the config values matched, except the `Title`. I've updated the scoping for `Title` and this can now be set at the store view. The remaining configuration values cannot be scoped to an individual store view.

**Comment by pmclain** [comment]
I've put this fix and #9, which creates problems when storing a card in the Magento Vault, in release 0.0.6. You many need to clean your composer cache to install the current release, explicitly define the version when adding the dependency ie: `composer require pmclain/module-stripe:0.0.6`
