### ISSUE TITLE
CC validation always fails

### ISSUE THREAD

**Issue by viperet** [pmclain/module-stripe#16]
When I enter any CC number, real or testing validation always fails.
I tracked problem down to 'validate-card-type' validation and 'allowedTypes' array;
It contains: [{"value":"AE","type":["American Express","American Express"]},{"value":"VI","type":["Visa","Visa"]},{"value":"MC","type":["MasterCard","MasterCard"]}]
Problem is 'type' field, it contains array with two identical elements, and in /Magento_Payment/js/model/credit-card-validation/validator.js code tries to match entered card type to one of the cards in 'allowedTypes'. And it always fails because of string == array comparision...

if (cardInfo.title == allowedTypes[i].type) {

I have another Stripe module installed, it works perfectly, but this - isn't...

**Comment by pmclain** [comment]
What module and magento version are you using? Starting with the stripe module v1.0.0 hosted fields are used and magento validation isn't applied to the fields.

Of course, you could continue to use the other module that's currently working for you.

**Comment by viperet** [comment]
I use Magento 2.1.2 and stripe module latest version (it 0.0.2 in module.xml but 1.0.1 in git).

![checkout 2017-10-23 16-13-00](https://user-images.githubusercontent.com/725651/31890808-2fab76be-b80d-11e7-95b1-054a4685301b.jpg)

**Comment by pmclain** [comment]
The screenshot is the payment form prior to this commit https://github.com/pmclain/module-stripe/commit/0654347c9107c69360985756c913c8d058e1ee0b#diff-f4088fe7bbda3d4ae3fadf698af749ff. You may want to check the static content deployed properly, or another module may have introduced a conflict.

**Comment by viperet** [comment]
Yes, the problem was in static content. After cleaning static content folder I got a new form, but checkout failed, it complained about not found class in magento_vault module. So I was unable to use this module on 2.1.2 (both old version and latest version of module), but upgrade to  2.1.8 solved all problems with stripe module, thanks!
