### ISSUE TITLE
Support of Managed account in Stripe

### ISSUE THREAD

**Issue by frostmoon** [pmclain/module-stripe#17]
Hello!
What about support of Managed account?
https://stripe.com/blog/managed-accounts-for-european-marketplaces

**Comment by pmclain** [comment]
Sorry for the delayed response. This does look interesting. Would you be able to explain the potential use case a bit more?

**Comment by frostmoon** [comment]
Hello! Sure!

One of the most popular example of using "managed account” on Stripe is Marketplace.
Marketplace is “online shop” where anyone can become a vendor. But if these vendors want to see something and receive money for theirs goods via Stripe - they have to make their own Stripe account.
But this way may be difficult for each one because they have to prepare a lot of documents and manage this accounts.

But, if owner of Marketplace will have “Managed account” option - he can create “sub account” for each vendor on that Marketplace via just one API request.
And if someone sell something - money will send to “Main” Stripe account (to Marketplace owner) and will “freeze” until transfer/delivery/etc not approved.
As soon as Marketplace will approve this order/money transfer/devliery - Marketplace make one more API  request and money from “Main” Stripe account go to “Vendors sub account”.

So cons of this way:
- Control money transfer until delivery/approve/etc
- Simple way for vendors who don’t want make his own fully-featured Stripe account
- Auto (or controlled) payout for each vendor

It just one example of using “Managed accounts” by Stripe

With regards, Sergey

**Comment by pmclain** [comment]
This feature would probably need to be tied to another vendor's module providing a multiple sellers feature. I didn't see any open source, but I didn't look very hard. If you know of one please pass it along and I'll take a look. I don't have motivation to add support for a paid module and most of the paid options I saw offer the Stripe integration as an upsell, so I doubt the vendor would provide a copy for developing a free alternative.

**Comment by pmclain** [comment]
Closing for now. This is not currently on the feature roadmap.
