### ISSUE TITLE
magento 2.0 support

### ISSUE THREAD

**Issue by deepak27892** [pmclain/module-stripe#28]
IS this module support in Magento 2.0 because at compile time its give error of magento core module of vault.

**Comment by deepak27892** [comment]
In Magento 2.0 there is no magento vault module .how is it run at magento 2.0

**Comment by deepak27892** [comment]
[ReflectionException]                                            
  Class Magento\Vault\Model\CreditCardTokenFactory does not exist  
                        
  [ReflectionException]                                            
  Class Magento\Vault\Model\CreditCardTokenFactory does not exist  
                                                   
  [Magento\Framework\Exception\LocalizedException]                                                                                 
  Source class "\Magento\Vault\Model\CreditCardToken" for "Magento\Vault\Model\CreditCardTokenFactory" generation does not exist.

**Comment by mysil2** [comment]
Are you using the right version for Magento 2.0 as per the Magento Version Requirements section in the readme?

**Comment by deepak27892** [comment]
yes I am using Magento 2.0.17.there is no value module

**Comment by mysil2** [comment]
The right version of the stripe module. There is different version that works for 2.0.x, 2.1.x and 2.2.x.

**Comment by deepak27892** [comment]
can you share  version of the stripe module who support in  magento 2.0.17

**Comment by mysil2** [comment]
Just check the readme under Magento Version Requirements section.

**Comment by deepak27892** [comment]
I have already checked my Magento version is 2.0.17 .When i have installed your module it gives error because in magento 2.0.17 there is no magento vault module .You are using magento vault dependency in your stripe module.
please check

**Comment by mysil2** [comment]
I am not talking about the Magento version, but the module-stripe version. I was hoping that you would read the readme of this module to find which version you should use. Obviously, you are unable to read the readme, so here it is:

Release | Magento Version
1.x.x | 2.2.x
1.x.x | 2.1.x
0.0.3 | 2.0.x

The table works in the following way:
The first column specify the version of module-stripe. The second column specify which Magento version the module-stripe version supports.

If you are using the latest version, only Magento 2.2.x is supported. Good luck!

**Comment by deepak27892** [comment]
Thanks for answer
Can you provide stripe version 0.0.3

**Comment by mysil2** [comment]
You can find it under Releases in this repository or you can require a specific version in the Magento composer configuration.

**Comment by deepak27892** [comment]
Thanks for answer
can you provide any testing credetial of stripe payament gateway

**Comment by mysil2** [comment]
Be sure to use your test api key from you stripe account and set stripe-module in test mode. Refer to https://stripe.com/docs/testing for a list of test payment card numbers.

**Comment by deepak27892** [comment]
Thanks for support and answer
