### ISSUE TITLE
Upgrade module-vault dependency to version 100.2.1

### ISSUE THREAD

**Issue by mysil2** [pmclain/module-stripe#3]
I have upgraded Magento the the latest version, but I'd love to test your Stripe module, and I ran: 
`composer require pmclain/module-stripe`

Got the following error:
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for pmclain/module-stripe ^0.0.4 -> satisfiable by pmclain/module-stripe[0.0.4].
>     - Conclusion: remove magento/module-vault 100.2.1
>     - Conclusion: don't install magento/module-vault 100.2.1
>     - pmclain/module-stripe 0.0.4 requires magento/module-vault 100.1.* -> satisfiable by magento/module-vault[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3, 100.1.0, 100.1.1].
>     - Can only install one of: magento/module-vault[100.2.1, 100.1.0-rc1].
>     - Can only install one of: magento/module-vault[100.2.1, 100.1.0-rc2].
>     - Can only install one of: magento/module-vault[100.2.1, 100.1.0-rc3].
>     - Can only install one of: magento/module-vault[100.2.1, 100.1.0].
>     - Can only install one of: magento/module-vault[100.2.1, 100.1.1].
>     - Installation request for magento/module-vault (locked at 100.2.1) -> satisfiable by magento/module-vault[100.2.1].

Any chance it'll work just changing the version in composer.json, or is it actually not compatible as it stands?

I see that the paypal module needs version 100.2.1, I'm not planning to use paypal but I'm new to Magento and have not found a solution for how to remove the paypal module in order to downgrade the module-vault.

**Comment by pmclain** [comment]
There's a very good chance I borked the composer.json. Can you confirm the Magento version and I'll test it out?

**Comment by mysil2** [comment]
Admin interface says Magento ver. 2.1.7.

**Comment by pmclain** [comment]
Thanks. I'll get a fresh install of 2.1.7 tonight and give it a try.

**Comment by pmclain** [comment]
I had failed to add the current version of `magento/module-vault` to `composer.json`. This has been corrected in the v0.0.5 release. You may need to clear your composer cache or explicitly state the version when attempting to install.
