### ISSUE TITLE
Issue with the test payment 

### ISSUE THREAD

**Issue by levikay** [pmclain/module-stripe#30]
When trying to process a test payment, I'm getting a 500 error on the following file,
/rest/default/V1/guest-carts/0810259eed24dfa520155452df583f7b/payment-information 

Am I missing something here?

**Comment by pmclain** [comment]
What’s the error?

**Comment by levikay** [comment]
Thank you for the quick responds  :)
This is the error I get back from the request
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/1398413697489"}]}}
Here's the request header and return header:
`Referrer Policy:no-referrer-when-downgrade

Response Headers

cache-control:no-store, no-cache, must-revalidate
content-type:application/json; charset=UTF-8
date:Tue, 23 Jan 2018 14:27:55 GMT
expires:Thu, 19 Nov 1981 08:52:00 GMT
pragma:no-cache
server:Apache
set-cookie:PHPSESSID=06da22498ed908a8135a42b58f11d979; expires=Tue, 23-Jan-2018 15:27:55 GMT; Max-Age=3600; path=/; domain=YYY.com; HttpOnly
status:500
x-content-type-options:nosniff
x-powered-by:PHP/7.1.7
x-xss-protection:1; mode=block

Request Headers

:authority:YYY.com
:method:POST
:path:/rest/default/V1/guest-carts/43cae6b63d7fb6bd2aff2e1e0c96cb5a/payment-information
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.9
cache-control:no-cache
content-length:585
content-type:application/json
cookie:store=default; form_key=5SBkX82zpkApf3Mf; private_content_version=5de85f1e0e530bb0d4f91d305c963635; mage-translation-storage=%7B%7D; mage-translation-file-version=%7B%7D; mage-cache-storage=%7B%7D; mage-cache-storage-section-invalidation=%7B%7D; mage-cache-sessid=true; mage-messages=; recently_viewed_product=%7B%7D; recently_viewed_product_previous=%7B%7D; recently_compared_product=%7B%7D; recently_compared_product_previous=%7B%7D; product_data_storage=%7B%7D; PHPSESSID=06da22498ed908a8135a42b58f11d979; section_data_ids=%7B%22directory-data%22%3A1516717587%2C%22cart%22%3A1516717650%2C%22messages%22%3A1516717650%7D
origin:https://YYY.com
pragma:no-cache
referer:https://YYY.com/checkout/
user-agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
x-requested-with:XMLHttpRequest

Request Payload

view source
{cartId: "43cae6b63d7fb6bd2aff2e1e0c96cb5a",…}
billingAddress
:
{countryId: "US", regionId: "13", regionCode: "CO", region: "Colorado", street: ["123 some st"],…}
cartId
:
"43cae6b63d7fb6bd2aff2e1e0c96cb5a"
email
:
"one@two.com"
paymentMethod
:
{method: "pmclain_stripe",…}`


Please let me know if you require any additional information. 
Thank you

**Comment by pmclain** [comment]
What is the error in api/1398413697489?

**Comment by levikay** [comment]
Where would I find that information?
Thank you

**Comment by levikay** [comment]
This is the error, 
"Fatal Error: 'Uncaught Error: Class 'Stripe\\Stripe' not found in \/home\/app\/code\/Pmclain\/Stripe\/Model\/Adapter\/StripeAdapter.php:42\nStack trace:\n#0 \/home\/app\/code\/Pmclain\/Stripe\/Model\/Adapter\/StripeAdapter.php(38): Pmclain\\Stripe\\Model\\Adapter\\StripeAdapter->initCredentials()\n#1 \/home\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(111): Pmclain\\Stripe\\Model\\Adapter\\StripeAdapter->__construct(Object(Pmclain\\Stripe\\Gateway\\Config\\Config), Object(Magento\\Framework\\Encryption\\Encryptor))\n#2 \/home\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Pmclain\\\\Stripe\\\\...', Array)\n#3 \/home\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Pmclain\\\\Stripe\\\\...')\n#4 \/home\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(144): Ma' in '\/home\/app\/code\/Pmclain\/Stripe\/Model\/Adapter\/StripeAdapter.php' on line 42"

**Comment by pmclain** [comment]
Stripes php-sdk is required by the module. Did you install using composer?

**Comment by pmclain** [comment]
Closing this issue. Feel free to reopen if adding the `stripe/stripe-php` package does not resolve.
