### ISSUE TITLE
Support for 3D secure?

### ISSUE THREAD

**Issue by FrederikNordahl** [pmclain/module-stripe#31]
Hey!

Is it on the roadmap, to add 3D secure support :) ?

/Frederik

**Comment by pmclain** [comment]
I hadn't thought about it, but it doesn't look too difficult. The hardest part will be handling the potential redirect offsite. Leaving the link to docs here for future reference https://stripe.com/docs/sources/three-d-secure

**Comment by FrederikNordahl** [comment]
Would be AWESOME for eu :D

Thanks a bunch for having a look :)

/F
rederik

**Comment by pmclain** [comment]
So I understand not initially including 3D secure was stereotypically American of me, and I apologize. I've spent a good chunk of the weekend trying to get it added and I've got an initial attempt in the [3d-secure branch](https://github.com/pmclain/module-stripe/tree/3d-secure). Would you be willing to assist with testing? It's a pretty large large change to the existing codebase. I need to go through and rework/write unit tests for the updates and hopefully some functional tests (now that MFTF is using Codeception 😄)

There are a few known issues at the moment:
1. There is no redirect when using Magento_InstantPurchase. I'm not sure this is going to be possible with the current structure of its placeOrder model.
2. Cards added to Magento_Vault during Admin order placement are not currently flagged as requiring 3D secure validation during frontend checkout. Shouldn't be hard to fix.
3. The mini-cart does not clear on order success when returning to complete order after leaving the site for 3D secure verification.

**Comment by simonmaass** [comment]
yeah wow - this would be great!
