### ISSUE TITLE
Version 0.0.3 not support Magento version 2.0.15

### ISSUE THREAD

**Issue by mcpeace** [pmclain/module-stripe#32]
Hi Pmclain,

This module is very helpful but there is difficulty for me.
As I investigate the 0.0.3 and Magento 2.0.15. Magento doesn't contain Magentuo_Vault and some elements. If I go to checkout, the page become blank and show error.

After I remove the Magento_Vault and try to put back `<!-- ko template: 'Magento_Payment/payment/cc-form' --><!-- /ko -->` to the form, the page works. However, at the payment page it returns an error.
`Failed to load resource: the server responded with a status of 400 (Bad Request)`
It fail to post JSON to the '/guest-carts/:quoteId/payment-information' and '/carts/mine/payment-information' page.

Thank you

Regards,
Tommy

**Comment by pmclain** [comment]
Double check the module version in your `composer.lock`, or `composer show -i pmclain/module-stripe`. v0.0.3 should not contain any reference to `Magento_Vault`. There should also be a descriptive error message, depending on the current deploy mode, returned in the response from the payment-information requests.

**Comment by mcpeace** [comment]
Hi Pmclain,

Sorry that my write up is a little bit chaos, but my store is really need to use the stripe in Magento v2.0.15. Let me re-state the issue here. 

The first time when i install this module, I have picked a wrong version, 1.00, for my magneto v2.0.15. After that, I found out that this Magento version has no Magento_Vault and then I change it back to module-stripe v0.03.
As I revocer my store backup and installed the version 0.03, I still can't active the Stripe Payment and I found out the this version of Magento doesn't contain Magentuo_Redirect on Sucess.

After I disable the Magentuo_Redirect on Sucess, the page and payment method works. However, it returns an error at the payment information page.
`Failed to load resource: the server responded with a status of 400 (Bad Request)`
It fail to post JSON to the '/guest-carts/:quoteId/payment-information' and '/carts/mine/payment-information' page.

Thousand thansks,
Tommy

**Comment by pmclain** [comment]
How did you download and install the module?

**Comment by pmclain** [comment]
What is the response from the server when you are seeing this message: `Failed to load resource: the server responded with a status of 400 (Bad Request)` There is probably a error report id referencing a file in `var/report`. I was unable to reproduce any issue installing the module via composer on 2.0.15.

**Comment by mcpeace** [comment]
As I use composer to install, it turns out error that magento 2.0.15 module-catalog is not the require 101.0.0 version but it is 100.0.14.

I have tried fresh install 2.0.15 to intall 0.0.3 stripe with composer, it turns out the same error.

**Comment by pmclain** [comment]
The module will no longer attempt to support Magento 2.0.x, since Magento is no longer providing security, quality, or documentation updates for this version. http://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.18CE.html
