### ISSUE TITLE
Issue with installation (doctrine/instantiator 1.1.0 requires php ^7.1)

### ISSUE THREAD

**Issue by stuartbuckell** [pmclain/module-stripe#33]
Hi there,

I've attempted to install your package via composer.  I receive the following error:

I'm using PHP 7.0.x as Magento isn't supporting 7.1/7.2  

I've tried Magento2 with 7.2 and get various errors (each() being depreciated)

Any ideas?  Thanks!

```Using version ^1.1 for pmclain/module-stripe
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.27) does not satisfy that requirement.
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.27) does not satisfy that requirement.
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.27) does not satisfy that requirement.
    - Installation request for doctrine/instantiator (locked at 1.1.0) -> satisfiable by doctrine/instantiator[1.1.0].```

**Comment by pmclain** [comment]
This doesn't look like anything that would be related to the Stipe module. The only two dependencies in composer.json are `magento/framework` and `stripe/stripe-php`. The latter does will not require any additional libraries, https://github.com/stripe/stripe-php/blob/bb3d932721977d1110b766b842f72cb32712b7f1/composer.json#L17. Magento, even in 2.3-develop, is using `doctrine/instantiator 1.0.5` https://github.com/magento/magento2/blob/b3353599af88ad50ce7d5b92abf5a705357ccc7d/composer.lock#L3825
