### ISSUE TITLE
Getting 500 (Internal Server Error)

### ISSUE THREAD

**Issue by sayanbasak** [pmclain/module-stripe#42]
Hello,
I am trying your Stripe module in my localhost Magento 2. My site url is like [my_machine_ip]/[project_name]. But I am continuously getting 500 internal server error while trying to place order. I have enabled Test mode and also have given Test secret key and publishable key. Can you please inform me for which reason is it happening?

**Comment by pmclain** [comment]
What's the error?

**Comment by sayanbasak** [comment]
Thank you for your reply. I have successfully run the module in my localhost. Then I installed the extension on my dev server and the below errors are showing:
Refused to execute script from 'http://naturalplaza.demoyourprojects.com/pub/static/version1523365325/frontend/Smartwave/porto_child/en_US/Pmclain_Stripe/js/view/payment/method-renderer/pmclain_stripe.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
console-output-handler.js:34 [2018-04-10 07:22:26] [ERROR] Failed to load the "Pmclain_Stripe/js/view/payment/method-renderer/pmclain_stripe" component.

**Comment by sayanbasak** [comment]
Hello,
I have solved the issue now. Thanks again. :-)
