### ISSUE TITLE
Guests cannot checkout

### ISSUE THREAD

**Issue by viktordodev** [pmclain/module-stripe#44]
I am getting a response in console "
https://mydomainxxx.co.uk/rest/default/V1/guest-carts/0ea6a2d913c8bede97ebec8f8399bc6a/payment-information" Not found 500 error.
This happens after I click on Place order.

The jquery stop is at : xhr.send( ( options.hasContent && options.data ) || null );

The actual order is sent to Stripe by the way but the order is not listed in backend and process is stuck on frontend without any warning message but a red bar.

Nothing in debug also. My ver. is 2.2.3

**Comment by pmclain** [comment]
What's in the log entry for the 500 error?

**Comment by viktordodev** [comment]
Hi, There is nothing in the error log on the server. But there is a 500 error in browser console that i mentioned already.

**Comment by viktordodev** [comment]
OK. Problem solved. It was the way of installation. I have installed it manually instead of using the composer.

**Comment by viktordodev** [comment]
Thank you.
