### ISSUE TITLE
Unknown error while placing order via stripe

### ISSUE THREAD

**Issue by itaims** [pmclain/module-stripe#47]
Hello,

I am facing an unknown error while making order payment through stripe payment gateway. 
I am using it in testing mode and when click on "Place Order" button it processes and show a red bar without any error.
Please check the below screenshot.

![capture](https://user-images.githubusercontent.com/26450677/40033656-f339e436-5816-11e8-842a-9bb0cf730d52.PNG)

How to resolve this error?

**Comment by pmclain** [comment]
Please add any errors you are receiving or detailed steps to reproduce on a clean installation of a supported Magento version.

**Comment by TandyCorp** [comment]
I just installed the 1.2.1 update on our Magento 2.2.3 installation, it is complaining about 'Invalid API Key Provided'. I expect the problem is the same only not showing in this screenshot. I tried re-entering the API key in the back end but that doesn't fix it.

**Comment by itaims** [comment]
Hello,



> :1142:"Fatal Error: 'Uncaught Error: Class 'Stripe\Stripe' not found in /home/instylem1x17/public_html/app/code/Pmclain/Stripe/Model/Adapter/StripeAdapter.php:47
> Stack trace:
> #0 /home/instylem1x17/public_html/app/code/Pmclain/Stripe/Model/Adapter/StripeAdapter.php(42): Pmclain\Stripe\Model\Adapter\StripeAdapter->initCredentials()
> #1 /home/instylem1x17/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Pmclain\Stripe\Model\Adapter\StripeAdapter->__construct(Object(Pmclain\Stripe\Gateway\Config\Config))
> #2 /home/instylem1x17/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Pmclain\\Stripe\\...', Array)
> #3 /home/instylem1x17/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Pmclain\\Stripe\\...')
> #4 /home/instylem1x17/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Mag' in '/home/instylem1x17/public_html/app/code/Pmclain/Stripe/Model/Adapter/StripeAdapter.php' on line 47";




I have tried to installed it so many times but i am getting the same error.

**Comment by pmclain** [comment]
The stripe sdk is missing. Following the composer installation instructions will fix.
