### ISSUE TITLE
Magento 2.2.4 new install causing sitewide errors

### ISSUE THREAD

**Issue by tony-terrible** [pmclain/module-stripe#49]
Any idea why this would be?

My rewrite rules seem to be changed and I can no longer access my admin url after installing the module according to your instructions. http://51.15.244.167/

This version of magento from today: Magento-CE-2.2.4_sample_data-2018-05-01-09-51-36.tar.gz

Linux/ARM64/Ubuntu Xenial

**Comment by pmclain** [comment]
Please add any errors you are receiving or detailed steps to reproduce on a clean installation of a supported Magento version.

**Comment by tony-terrible** [comment]
I think I have it sorted out. I think it was because I didn't set a base URL during install (though it was working before installing your module.)

I set one and it didn't do anything, so I posted this message, but then i realized I forgot to clear the cache which I did just this moment and it is working now. 

Sorry!
