### ISSUE TITLE
Getting network error

### ISSUE THREAD

**Issue by itaims** [pmclain/module-stripe#50]
Hello,

After setting up the stripe module, when i try to make payment, i am getting the following error.

> Unexpected error communicating with Stripe.  If this problem persists, let us know at support@stripe.com.\n\n(Network error [errno 77]: error setting certificate verify locations:\n  CAfile: \n  CApath: none)

How to resolve this issue?

Thanks,

**Comment by itaims** [comment]
i have installed the the ssl to the website but still getting the same error. 
Please check the attached screenshot for SSL and  the error.

![capture](https://user-images.githubusercontent.com/26450677/40647501-9df91a26-6349-11e8-8030-c1012a9bb053.PNG)

**Comment by pmclain** [comment]
The error is not related to the SSL certificate on your domain. This error means that cURL is misconfigured on your server. Most probably curl ssl(open SSL) is broken or it simply can't find the certificates at the pointed location.

**Comment by TandyCorp** [comment]
It could be that your system clock is not set correctly, if the time is wrong cURL will not be able to establish a secure connection to the stripe server.

**Comment by pmclain** [comment]
Closing: This does not appear related to the module. Please reopen if the error continues after correcting your server configuration.
