### ISSUE TITLE
Checkout messages are not the ones returned by Stripe

### ISSUE THREAD

**Issue by samuel27m** [pmclain/module-stripe#53]
Using the Stripe testing keys, I went ahead and tried to test some of the errors that Stripe provides as example in their dev docs, and the messages shown in the checkout are not the ones returned by Stripe.

Example Card : 4000000000000069
Should give out message: "Your card is expired"
Message it actually gives: Transaction has been declined. Please try again later.

**Comment by pmclain** [comment]
This is by design and follows convention used by core Magento payment integrations. Providing additional decline information could make sites using this module targets for those testing card numbers in bulk.
