### ISSUE TITLE
Error install 

### ISSUE THREAD

**Issue by zhiyicai** [pmclain/module-stripe#54]
Problem 1
    - Conclusion: remove magento/product-community-edition 2.1.13
    - Conclusion: don't install magento/product-community-edition 2.1.13
    - Installation request for pmclain/module-stripe ^2.0 -> satisfiable by pmclain/module-stripe[v2.0.0].
    - Installation request for magento/product-community-edition 2.1.13 -> satisfiable by magento/product-community-edition[2.1.13].
    - magento/product-community-edition 2.1.13 requires magento/framework 100.1.13 -> satisfiable by magento/framework[100.1.13].
    - Can only install one of: magento/framework[101.0.5, 100.1.13].
    - Can only install one of: magento/framework[101.0.5, 100.1.13].
    - Can only install one of: magento/framework[100.1.13, 101.0.5].
    - pmclain/module-stripe v2.0.0 requires magento/framework ~101.0.0||~100.3.0-dev -> satisfiable by magento/framework[101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc23, 101.0.0-rc30, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.4, 101.0.5].
    - magento/framework 101.0.0-rc21 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc22 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc23 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc30 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.1 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.2 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.3 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.4 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - Conclusion: don't install composer/composer 1.4.1

**Comment by pmclain** [comment]
v2.x does not support Magento 2.1.x. Refer to the compatibility table in the readme.
