### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by terrybakshi** [pmclain/module-stripe#7]
i am trying to install extension but its giving me error of URL authentication through composer please check the screenshot. Can you please help rectify this issue. Thanks
![fullsize_distr](https://user-images.githubusercontent.com/13229022/29268138-e96a7ff2-812e-11e7-941b-6e5ee566e6ea.png)

**Comment by pmclain** [comment]
What installation method did you use for this Magento instance and which version are you currently attempting to install the Stripe module on?

**Comment by terrybakshi** [comment]
Thanks for reply i am using version 2.1.8 Community edition. as per your installation guide i just went to my ssh and tried to run the command in magento root and got this error.

**Comment by pmclain** [comment]
You need to use an interactive shell because the Magento repositories, listed as dependencies, require access keys. I've added manual installation instructions to the README, https://github.com/pmclain/module-stripe/blob/master/README.md

**Comment by terrybakshi** [comment]
ok thanks i will try this now if any issue will let you know.

**Comment by terrybakshi** [comment]
Thanks much appreciate your help yes its installed now.

**Comment by terrybakshi** [comment]
ok on checkout page its giving error but not showing the error message can you please check https://www.toydeals.com.au

**Comment by pmclain** [comment]
That's probably because the Stripe class is missing if you followed the manual install instructions. You will need to add the Stripe-sdk to the project. The easiest way is with composer. In the magento install root run:  `composer require stripe/stripe-php:3.7.0` I'm updating the install instructions now.

**Comment by terrybakshi** [comment]
ok same issue here first it started updating the composer and then same error 
![stripe fullsize_distr](https://user-images.githubusercontent.com/13229022/29271875-05733ae2-8141-11e7-9873-5b9c63ba258f.png)
came

**Comment by pmclain** [comment]
You need to use an interactive shell so you can input your access keys for the Magento repos.

**Comment by terrybakshi** [comment]
ok can you tell me the method as i am not aware of it pls.

Thanks

**Comment by pmclain** [comment]
Sorry, this is not the proper forum for that. You can manually install the stripe sdk following their instructions , https://github.com/stripe/stripe-php#manual-installation, and adding the `require_once` declaration as described in their documentation to the `Pmclain\Stripe\Model\Adapter\StripeAdapter` class. Doing so has not been tested.

**Comment by terrybakshi** [comment]
ok let me try it out, if i am not able to do it would you please be able to install it for me thanks

**Comment by terrybakshi** [comment]
sorry i am not able to do it, would you be able to install it for me pls.

Thanks
