### ISSUE TITLE
Fatal Error: 'Uncaught Error: Class 'Stripe\\Stripe' not found

### ISSUE THREAD

**Issue by pratikkamani** [pmclain/module-stripe#71]
"Fatal Error: 'Uncaught Error: Class 'Stripe\\Stripe' not found in \/home\/mustperf\/public_html\/MUSTPERFUME.CO.UK\/app\/code\/Pmclain\/Stripe\/Model\/Adapter\/StripeAdapter.php:47\nStack trace:\n#0 \/home\/mustperf\/public_html\/MUSTPERFUME.CO.UK\/app\/code\/Pmclain\/Stripe\/Model\/Adapter\/StripeAdapter.php(42): Pmclain\\Stripe\\Model\\Adapter\\StripeAdapter->initCredentials()\n#1 \/home\/mustperf\/public_html\/MUSTPERFUME.CO.UK\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(111): Pmclain\\Stripe\\Model\\Adapter\\StripeAdapter->__construct(Object(Pmclain\\Stripe\\Gateway\\Config\\Config))\n#2 \/home\/mustperf\/public_html\/MUSTPERFUME.CO.UK\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Pmclain\\\\Stripe\\\\...', Array)\n#3 \/home\/mustperf\/public_html\/MUSTPERFUME.CO.UK\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Pmclain\\\\Stripe\\\\...')\n#4 \/home\/mustperf\/public_html\/MUSTPERFU' in '\/home\/mustperf\/public_html\/MUSTPERFUME.CO.UK\/app\/code\/Pmclain\/Stripe\/Model\/Adapter\/StripeAdapter.php' on line 47"

dashboard.stripe.com have a proper log for a request that means there is no any API issue. The issue is from your code. can you please guide or fix this issue ASAP.

**Comment by pmclain** [comment]
Not installing via composer means you are responsible for including any dependencies defined in composer.json.

**Comment by pratikkamani** [comment]
So, can I uninstall manual and again install via composer.json?

**Comment by huykon** [comment]
I have same problem. how to fix it?
