### ISSUE TITLE
 Unsupported declare 'strict_types' in  Magento V-2.3.0

### ISSUE THREAD

**Issue by bharatvimirlab** [pmclain/module-stripe#72]
The extension shows error: 

Unsupported declare 'strict_types' in /../vendor/magento/inventory-composer-installer/src/Plugin.php on line 6
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /../vendor/magento/inventory-composer-installer/src/Plugin.php on line 55"

**Comment by pmclain** [comment]
> Unsupported declare 'strict_types' in /../vendor/magento/inventory-composer-installer/src/Plugin.php on line 6

This file is part of MSI and not related to this module.
