### ISSUE TITLE
Fatal Error: 'Class 'Pmclain\Stripe\Gateway\Request\Customer' not found' in '/vendor/pmclain/module-stripe/Gateway/Request/PaymentDataBuilder.php' on line 124

### ISSUE THREAD

**Issue by shaileshjangir** [pmclain/module-stripe#9]
When when payment with Save Card option checked getting issue of:

Fatal Error: 'Class 'Pmclain\Stripe\Gateway\Request\Customer' not found' in '/vendor/pmclain/module-stripe/Gateway/Request/PaymentDataBuilder.php' on line 124

**Comment by pmclain** [comment]
The import statement for `Stripe\Customer` is missing from the `PaymentDataBuilder` class. I will get a fix committed and make a bugfix release in the next 24hrs. Below is a temporary patch to make it work until the release (it's just adding `use Stripe\Customer;` to the import declaration block).

```
diff --git a/Gateway/Request/PaymentDataBuilder.php b/Gateway/Request/PaymentDataBuilder.php
index e61be12..8325e76 100755
--- a/Gateway/Request/PaymentDataBuilder.php
+++ b/Gateway/Request/PaymentDataBuilder.php
@@ -21,6 +21,7 @@ use Magento\Payment\Gateway\Request\BuilderInterface;
 use Pmclain\Stripe\Helper\Payment\Formatter;
 use Magento\Customer\Model\Session;
 use Magento\Customer\Api\CustomerRepositoryInterface;
+use Stripe\Customer;
 
 class PaymentDataBuilder implements BuilderInterface
 {
```
